export const SET_ENTRY = 'SET_ENTRY';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_LOADING = 'FETCH_COINS_LOADING';
export const FETCH_COINS_ERROR = 'FETCH_COINS_ERROR';
export const FETCH_EXCHANGES_SUCCESS = 'FETCH_EXCHANGES_SUCCESS';
export const FETCH_EXCHANGES_LOADING = 'FETCH_EXCHANGES_LOADING';
export const FETCH_EXCHANGES_ERROR = 'FETCH_EXCHANGES_ERROR';
